head: 
   favicon: "/images/facicon1.png" #  the favicon
   high_res_favicon: "/images/favicon2.png" #  the favicon using high quality format
   apple_touch_icon: "/images/favicon2.png" # the iOS Home button icon
   keywords: "jekyll blog PKM AI" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: false # meng

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "/images/c.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: false
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: false
  
comment:
  used: "livere" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "wangc" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: 'MTAyMC8zMTI1OS83ODA4'
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components: 
    - c 
    - c++
    - php
    - sql
    - python
  plugins: 

mathjax: true

google_analytics: "UA-107846901-1"  # google analytics code

baidu_site_verification: "cUWDgJtPLR"  # baidu site verification code
google_site_verification: "google7c87d37893759bbc.html"  # google search console verification code

baidu_auto_push: true  # if you used baidu auto push to commit links

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js